name: Publish Package

on:
  release:
    types: [created]  

jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@brunosps'

      - name: Install dependencies
        run: npm install 
        
      - name: Test
        run: npm test
        continue-on-error: true
        
      - name: Build
        run: NODE_OPTIONS=--no-deprecation npm run build

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
